name: Go

on:
  push:
    branches: [ PBI-2-dbmanagelink ]
  pull_request:
    branches: [ PBI-2-dbmanagelink ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v3
      # with:
      #   go-version: 1.19
    
    # Install all the dependencies
    - name: start
      run: |
        go version
        go mod init github.com/bagasalim/simas 
      working-directory: backend

    - name: test
      run : |
        go mod init
        go test -v ./auth 
      working-directory: backend
