name: Go

on:
  push:
    branches: [ PBI-2-dbmanagelink ]
  pull_request:
    branches: [ PBI-2-dbmanagelink ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16

    - name: Go initialization
        run : go mod init
        working-directory: backend

    - name: test
        run : go test -cover -v ./auth
        working-directory: backend
